In [1]:
import matplotlib.pyplot as plt
import os
import numpy as np
import pandas as pd
import itertools
%matplotlib inline

In [2]:
COMMS_DATA = {
    'buffer_sps_500':np.zeros((9,5),dtype=np.int16),
    'buffer_sps_500_ao':np.zeros((5,),dtype=np.int16),
    'pace_markers': 0,
    'paceInfo': [np.zeros((3,),dtype=np.int16),0],
    'ecgCount': 0
}

In [3]:
l=[]

In [4]:
l.append(COMMS_DATA)

In [5]:
l

[{'buffer_sps_500': array([[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]], dtype=int16),
  'buffer_sps_500_ao': array([0, 0, 0, 0, 0], dtype=int16),
  'ecgCount': 0,
  'paceInfo': [array([0, 0, 0], dtype=int16), 0],
  'pace_markers': 0}]

In [6]:
l.append(COMMS_DATA)

In [7]:
x = l[0]

In [8]:
type(x)

dict

In [12]:
x

{'buffer_sps_500': array([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=int16),
 'buffer_sps_500_ao': array([0, 0, 0, 0, 0], dtype=int16),
 'ecgCount': 0,
 'paceInfo': [array([0, 0, 0], dtype=int16), 0],
 'pace_markers': 0}

In [13]:
x['buffer_sps_500']

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [20]:
l[0]['buffer_sps_500'][0] = [1,2,3,4,5]

In [21]:
l[0]['buffer_sps_500'][0]

array([1, 2, 3, 4, 5], dtype=int16)

In [24]:
x.keys()

dict_keys(['buffer_sps_500', 'buffer_sps_500_ao', 'pace_markers', 'paceInfo', 'ecgCount'])

In [41]:
tld = '5EEDDECA004E2081777E007A000900010004009500A600B100B10002000100400079003900010004007D0085007F00730002000400B200BF00B400A000030004003400380035002E00040004002D002F0028001B000500040059005F0052003B0006000400B700C300B500980007000400D900E800DC00C30008000400C900D700CF00BA0009000400A900B600AE009C002100010040007B00060001000100000002000104541B52'

In [42]:
sample_count = int(tld[32:36], 16)

In [43]:
sample_count

4

In [44]:
#l[0]['buffer_sps_500'][0] = [int(tld[i:i+4],16) for i in range(104,120,4)]
for i in range(104,120,4):
    print(i)

104
108
112
116


In [45]:
l[0]['buffer_sps_500'][0] = [int(tld[i:i+4],16) for i in range(104,124,4)]

In [46]:
l[0]['buffer_sps_500'][0]

array([178, 191, 180, 160,   3], dtype=int16)